### PR TITLE
actual perfection

### PR DESCRIPTION
**Pull request by MauriceButler**

### CODE REVIEW

**Comment by KoryNunn** [comment]
pull `coolKid` from `window.hash.slice(1)` and I'll `lgtm()`

**Comment by KoryNunn** [comment]
Also rename var to `australiasLeadingJavascriptDeveloper`

**Comment by MauriceButler** [comment]
dun

**Comment by KoryNunn** [comment]
:/

**Comment by KoryNunn** [comment]
I demauriced it.

**Pull request merged**
